name: settpay_ui
description: UI widgets / snippets for SettPay
version: 1.0.0
homepage: https://www.setheum.xyz

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
